name: CI/CD Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Java toolchain
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Add gradlew permission
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test

  build-and-deploy:
    name: Build Docker image and deploy to EC2
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and save Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: be-profile:latest

      - name: Save Docker image as tar file
        run: |
          docker save be-profile:latest > be-profile.tar

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "be-profile.tar,docker-compose.yml,start-app.sh"

      - name: Execute remote commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            docker load < be-profile.tar
            chmod +x start-app.sh
            ./start-app.sh