name: Docker-Build-and-EC2-Deploy

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    name: Build Docker image and deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and save Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: be-profile:latest

      - name: Save Docker image as tar file
        run: |
          docker save be-profile:latest > be-profile.tar

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "be-profile.tar,docker-compose.yml,start-app.sh"

      - name: Execute remote commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            docker load < be-profile.tar
            chmod +x start-app.sh
            ./start-app.sh